### ISSUE TITLE
OciError ORA-06502: PL/SQL: numeric or value error when try to read Object returned from procedure

### ISSUE THREAD

**Issue by AndrewKhitrin** [kubo/rust-oracle#16]
Hi,

We try to use rust-oracle for call function that returns an object and get Oracle Error.

This is the example of errors encountered in Rust Oracle Crate

ORA-06502: PL/SQL: numeric or value error
While trying to execute a query INTO object.
If return data contains extra long fields (with unspecified length boundary of 200-300-500 UTF chars) error is produced by connection driver.
In case the same query is executed via other DB client(like DBeaver) result is displayed in full with no errors raised.
Notes:

The response overall length somehow affects this behaviour.
If Only one field (Attribute A) has extra long data, but still matches the unspecified maximum length boundary, it appears to return correctly.
If there are other fields in response (Attributes B C D), summarised length of all fields is compared against unspecified char length limit.

Steps to reproduce 

1.Create database objects 

```SQL
CREATE OR REPLACE TYPE T_OBJ_LONG AS OBJECT (
      data1 VARCHAR2(500 CHAR),
      data2 VARCHAR2(500 CHAR),
      data3 VARCHAR2(500 CHAR),
      data4 VARCHAR2(500 CHAR)
) ;

CREATE OR REPLACE FUNCTION t_test_long(v_count IN NUMBER) RETURN T_OBJ_LONG
IS 
 v_res T_OBJ_LONG;
BEGIN
 v_res := T_OBJ_LONG(
     dbms_random.string('U',v_count),
     dbms_random.string('U',v_count),
     dbms_random.string('U',v_count),
    dbms_random.string('U',v_count)
 ); 
 RETURN v_res;
END;
```

2. Try to fetch object with rust-oracle

```RUST
use oracle::{ Connection, sql_type, Error };
use oracle::sql_type::{ObjectType, Object};

fn main() {

    static SQL_TEST:&str = "CALL t_test_long(:v_count) INTO :v_result ";

    let conn: Connection = Connection::connect("[USER]", "[PASS]", "//[SERVER]:[PORT]/[SERVICE NAME]").unwrap();

    let mut result_type = conn.object_type("T_OBJ_LONG").unwrap();
    let mut stmt = conn.prepare(SQL_TEST, &[]).unwrap();

    //Everythig works fine when we return 4 string with 10 chars each

    stmt.execute(&[
        &10,
        &sql_type::OracleType::Object(result_type)]
    ).unwrap();

    let v_result: sql_type::Object = stmt.bind_value("v_result").unwrap();

    println!("{:?} + {:?} + {:?} + {:?}",
             v_result.get::<String>("DATA1").unwrap().len(),
             v_result.get::<String>("DATA2").unwrap().len(),
             v_result.get::<String>("DATA3").unwrap().len(),
             v_result.get::<String>("DATA4").unwrap().len(),
    );

    // Reproduce ORA-06502: PL/SQL: numeric or value error
    // Executing a query with extra long data return (500 chars)

    result_type = conn.object_type("T_OBJ_LONG").unwrap();

    stmt.execute(&[
        &500,
        &sql_type::OracleType::Object(result_type)]
    ).unwrap();

    let v_result: sql_type::Object = stmt.bind_value("v_result").unwrap();

    println!("{:?} + {:?} + {:?} + {:?}",
             v_result.get::<String>("DATA1").unwrap().len(),
             v_result.get::<String>("DATA2").unwrap().len(),
             v_result.get::<String>("DATA3").unwrap().len(),
             v_result.get::<String>("DATA4").unwrap().len(),
    );

}
```

3. Output 

```
Running `target/debug/rust_oracle_issue`
10 + 10 + 10 + 10
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: OciError(DbError { code: 6502, offset: 0, message: "ORA-06502: PL/SQL: numeric or value error", fn_name: "dpiStmt_execute", action: "execute" })', src/libcore/result.rs:1084:5
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.34/src/backtrace/libunwind.rs:88
   1: backtrace::backtrace::trace_unsynchronized
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.34/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:47
   3: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:36
   4: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:200
   5: std::panicking::default_hook
             at src/libstd/panicking.rs:214
   6: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:477
   7: std::panicking::continue_panic_fmt
             at src/libstd/panicking.rs:384
   8: rust_begin_unwind
             at src/libstd/panicking.rs:311
   9: core::panicking::panic_fmt
             at src/libcore/panicking.rs:85
  10: core::result::unwrap_failed
             at src/libcore/result.rs:1084
  11: core::result::Result<T,E>::unwrap
             at /rustc/625451e376bb2e5283fc4741caa0a3e8a2ca4d54/src/libcore/result.rs:852
  12: rust_oracle_issue::main
             at src/main.rs:34
  13: std::rt::lang_start::{{closure}}
             at /rustc/625451e376bb2e5283fc4741caa0a3e8a2ca4d54/src/libstd/rt.rs:64
  14: std::rt::lang_start_internal::{{closure}}
             at src/libstd/rt.rs:49
  15: std::panicking::try::do_call
             at src/libstd/panicking.rs:296
  16: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:80
  17: std::panicking::try
             at src/libstd/panicking.rs:275
  18: std::panic::catch_unwind
             at src/libstd/panic.rs:394
  19: std::rt::lang_start_internal
             at src/libstd/rt.rs:48
  20: std::rt::lang_start
             at /rustc/625451e376bb2e5283fc4741caa0a3e8a2ca4d54/src/libstd/rt.rs:64
  21: main
  22: __libc_start_main
  23: _start
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

---
OS : Linux
Oracle : Oracle Database 12c Standard Edition Release 12.2.0.1.0 - 64bit Production
Client : oracle-instantclient19.3-basic-19.3.0.0.0-1.x86_64

**Comment by kubo** [comment]
@AndrewKhitrin 
Could you use `"BEGIN :v_result := t_test_long(:v_count); END;"` instead of `"CALL t_test_long(:v_count) INTO :v_result "`?

> In case the same query is executed via other DB client(like DBeaver) result is displayed in full with no errors raised.

How do you execute it via DBeaver? The tool replaces variables with user-supplied values before executing statements instead of supporting real host variables. Perhaps there is a limit of the maximum data length of host variables when the statement is `CALL`.

**Comment by AndrewKhitrin** [comment]
@kubo, thanks for you reply!

We've tried to execute your example and it works fine when the length is 500... but the error reappears when we change it to 1500 :( 

```RUST
use oracle::{ Connection, sql_type, Error };
use oracle::sql_type::{ObjectType, Object};

fn main() {

    static SQL_TEST:&str = "BEGIN :v_result := t_test_long(:v_count); END;";
    //                                        ^^^^^ New CALL statment

    let conn: Connection = Connection::connect("C##tpc", "tpc", "//proton:1522/tpc").unwrap();

    let mut result_type = conn.object_type("C##TPC.T_OBJ_LONG").unwrap();
    let mut stmt = conn.prepare(SQL_TEST, &[]).unwrap();

    //Everythig works fine when we return 4 string with 10 chars each

    stmt.execute(&[
        &sql_type::OracleType::Object(result_type)
        ,&10]
    ).unwrap();

    let v_result: sql_type::Object = stmt.bind_value("v_result").unwrap();

    println!("{:?} + {:?} + {:?} + {:?}",
             v_result.get::<String>("DATA1").unwrap().len(),
             v_result.get::<String>("DATA2").unwrap().len(),
             v_result.get::<String>("DATA3").unwrap().len(),
             v_result.get::<String>("DATA4").unwrap().len(),
    );

    // Reproduce ORA-06502: PL/SQL: numeric or value error
    // Executing a query with extra long data return (1500 chars)

    result_type = conn.object_type("C##TPC.T_OBJ_LONG").unwrap();

    stmt.execute(&[
        &sql_type::OracleType::Object(result_type)
        ,&1500] // Length 1500
    ).unwrap();


    let v_result: sql_type::Object = stmt.bind_value("v_result").unwrap();

    println!("{:?} + {:?} + {:?} + {:?}",
             v_result.get::<String>("DATA1").unwrap().len(),
             v_result.get::<String>("DATA2").unwrap().len(),
             v_result.get::<String>("DATA3").unwrap().len(),
             v_result.get::<String>("DATA4").unwrap().len(),
    );

}
```
Output :
```
10 + 10 + 10 + 10
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: OciError(DbError { code: 6502, offset: 0, message: "ORA-06502: PL/SQL: numeric or value error: character string buffer too small\nORA-06512: at \"C##TPC.T_TEST_LONG\", line 5\nORA-06512: at line 1", fn_name: "dpiStmt_execute", action: "execute" })', src/libcore/result.rs:1084:5
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.34/src/backtrace/libunwind.rs:88
   1: backtrace::backtrace::trace_unsynchronized
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.34/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:47
   3: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:36
   4: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:200
   5: std::panicking::default_hook
             at src/libstd/panicking.rs:214
   6: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:477
   7: std::panicking::continue_panic_fmt
             at src/libstd/panicking.rs:384
   8: rust_begin_unwind
             at src/libstd/panicking.rs:311
   9: core::panicking::panic_fmt
             at src/libcore/panicking.rs:85
  10: core::result::unwrap_failed
             at src/libcore/result.rs:1084
  11: core::result::Result<T,E>::unwrap
             at /rustc/625451e376bb2e5283fc4741caa0a3e8a2ca4d54/src/libcore/result.rs:852
  12: rust_oracle_issue::main
             at src/main.rs:34
  13: std::rt::lang_start::{{closure}}
             at /rustc/625451e376bb2e5283fc4741caa0a3e8a2ca4d54/src/libstd/rt.rs:64
  14: std::rt::lang_start_internal::{{closure}}
             at src/libstd/rt.rs:49
  15: std::panicking::try::do_call
             at src/libstd/panicking.rs:296
  16: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:80
  17: std::panicking::try
             at src/libstd/panicking.rs:275
  18: std::panic::catch_unwind
             at src/libstd/panic.rs:394
  19: std::rt::lang_start_internal
             at src/libstd/rt.rs:48
  20: std::rt::lang_start
             at /rustc/625451e376bb2e5283fc4741caa0a3e8a2ca4d54/src/libstd/rt.rs:64
  21: main
  22: __libc_start_main
  23: _start
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

Process finished with exit code 101

```

So the behaviour is quite unstable. Could you please have a look where a problem can arise from? We really need some kind of stability to utilize your otherwise great library in our production code.

P.S.
We used DBeaver only for testing puproses, i.e. to check the statement for correctness, please do not mind it :)

P.P.S.
Thanks for your work on the library! :)

**Comment by kubo** [comment]
It works fine for me. I'm using Oracle 18.3.0.0.0 on Linux (both client and server).

Have you recreated `T_OBJ_LONG` to change the character size from 500 to 1500?

The error message in the first post was simply `ORA-06502: PL/SQL: numeric or value error`.
It was changed in your second post as follows:
```
ORA-06502: PL/SQL: numeric or value error: character string buffer too small
ORA-06512: at "C##TPC.T_TEST_LONG", line 5
ORA-06512: at line 1
```
It failed inside of `T_TEST_LONG`. I guess that it tried to set 1500 characters to varchar2(500 char) data type.

**Comment by AndrewKhitrin** [comment]
Yes, it works. Looks like I forgot to expand varchar2 fields of data type.

Its my fault.

Thank you very much for help !
